#pragma once

// Map

#define MIN_ROOM_COUNT 10
#define MAX_ROOM_COUNT 20
#define MAX_ROOM_WEIGHT 15
#define MAX_ROOM_HEIGHT 15
#define MIN_ROOM_HEIGHT 7
#define MIN_ROOM_WEIGHT 7
#define MIN_X 20
#define MIN_Y 20
#define MAX_X 100
#define MAX_Y 130
#define CORRIDOR_GENERATE_TRIES 40
#define EXIT_GENERATE_TRIES 100

#define MAP_Y_SIZE MIN_Y+MAX_Y

#define MAP_X_START 4
#define MAP_X_END 45
#define MAP_Y_START 6
#define MAP_Y_END 129

// COLOR
#define COLOR_BLACK 30
#define COLOR_RED 31
#define COLOR_GREEN 32
#define COLOR_YELLOW 33
#define COLOR_BLUE 34
#define COLOR_MAGENTA 35
#define COLOR_CYAN 36
#define COLOR_WHITE 37

#define COLOR_BRIGHT_BLACK 90
#define COLOR_BRIGHT_RED 91
#define COLOR_BRIGHT_GREEN 92
#define COLOR_BRIGHT_YELLOW 93
#define COLOR_BRIGHT_BLUE 94
#define COLOR_BRIGHT_MAGENTA 95
#define COLOR_BRIGHT_CYAN 96
#define COLOR_BRIGHT_WHITE 97

// Other

#define MAX_FRAME 10
